### ISSUE TITLE
Child node to configure

### ISSUE THREAD

**Issue by pierloui** [me1ifaro/MelifaroBookingBundle#5]
I am getting this error, any idea to what it could be related to?

InvalidConfigurationException in ArrayNode.php line 240:
The child node "entity_class" at path "melifaro_booking" must be configured.

**Comment by me1ifaro** [comment]
@pierloui 
Add to your config.yml
```
melifaro_booking:
    entity_class: Vendor\Bundle\Entity\Concrete
```
